name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: set up to node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: build
        run: npm test

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-avzr"
            SOURCE: ""
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: "root"
            TARGET: "/data/server/tmp"
            EXCLUDE: "/dist/, /node_modules/"
            SCRIPT_BEFORE: |
              whoami
              ls -al
            SCRIPT_AFTER: |
              whoami
              ls -al
              echo $RSYNC_STDOUT
